version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "qqbounty"
phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm build
    post_build:
        commands:
            - echo "$CODEBUILD_BUILD_SUCCEEDING"
            # if build succeeds copy the dist folder into the s3 bucket
            - |
                if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
                    aws s3 cp /build/ s3://${S3_BUCKET} --recursive;
                    echo "Build completed on date";
                fi
artifacts:
    files:
        - '**/*'
    base-directory: '/build/*'
    discard-paths: yes
