version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "1810-redux-nchristian"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - cd client/ && npm install
    build:
        commands:
            - echo Build started on `date`
            - cd client/ && npm run build
    post_build:
        commands:
            - echo "$CODEBUILD_BUILD_SUCCEEDING"
            # if build succeeds copy the dist folder into the s3 bucket
            - |
                if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
                    aws s3 cp "/client/build/" "--recursive";
                    echo "Build completed on date";
                fi
artifacts:
    files:
        - '**/*'
    base-directory: 'build*'
    discard-paths: yes